spring.application.name=LibrarySpringProject

spring.datasource.url=jdbc:mysql://localhost:3306/test
spring.datasource.username=root
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update

app.admin.email=admin@library.com
app.admin.userName=Admin
app.admin.password=password123

jwt.secret=my-password-for-my-first-library-project-using-spring-boot